### ISSUE TITLE
Wish to support sort headers of the HTTP request

### ISSUE THREAD

**Issue by shuxiao9058** [ddliu/go-httpclient#23]
see title

**Comment by ddliu** [comment]
Do you mean you want to control the order of the headers to be sent? Why you need it, could you please show me your case?

Currently the implement of `go-httpclient` headers are stored in a map, which has no order.

**Comment by shuxiao9058** [comment]
我想用作网络爬虫，固定次序能够防止服务端检测出来。

**Comment by ddliu** [comment]
暂时不支持，另外此库是基于golang的http库，golang的也是无序的

**Comment by shuxiao9058** [comment]
嗯，目前我采取的方案是修改标准库，能够实现自己想要的功能，但是感觉不太好用。
