### ISSUE TITLE
怎么取消正在请求的client

### ISSUE THREAD

**Issue by fzkun** [ddliu/go-httpclient#32]

**Comment by afghanistanyn** [comment]
may be you can try context.WithCancel

**Comment by ddliu** [comment]
> may be you can try context.WithCancel

Thank you for your idea @afghanistanyn.

@fzkun It's now supported, see test file for example: https://github.com/ddliu/go-httpclient/blob/7e31de4a0428a364effb5d16b85a539056280793/httpclient_test.go#L755
