### ISSUE TITLE
What request parameters can be customized?

### ISSUE THREAD

**Issue by ResistanceIsUseless** [ddliu/go-httpclient#43]
Are you able to set the following? If so is there a recommended way?
- HTTP Version HTTP/0.9 , HTTP/1 , HTTP2
- Host Header
- Path

Also, does it support concurrent requests? I see you can create multiple requests but I want to create something similar to channels to handle a bunch of requests to separate hosts?

**Comment by ddliu** [comment]
HTTP Version (Proto) is not supported.

Host Header / Path/ Concurrent are supported, refer to README for more details.
