### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by zollty** [ddliu/go-httpclient#46]
using `httpclient.Begin()` in multithreading environment（some threads runing  or sleeping long time, but we keep the total number of threads below the threshold, less than 30）, but the socket open files is increasing all the time. using command `ls -p {pid} | wc -l`, we can see the number is increasing slow but never reducing。When we ran the program two days，socket open files reached 65539 then start to report errors “socket: too many open files”。

this may caused by reusing the Transport of golang http client， and this problem should be easy to reproduce。the code like this:
```go
	for i := 0; i < w.ThreadNum; i++ {
		go w.doTest()
		time.Sleep(10 * time.Millisecond)
	}
```

**Comment by ddliu** [comment]
Have you released the response resource?

You can close it by calling `defer response.Close()`. If you read the response by calling `response.ReadAll()`, it'll be handled automatically.
