### ISSUE TITLE
defaultClient concurrency is not safe

### ISSUE THREAD

**Issue by sunyuan300** [ddliu/go-httpclient#48]
```go
package main
import (
	"github.com/ddliu/go-httpclient"
	"time"
)

func main() {
	for i := 0; i <20;i++ {
		go do()
	}

	time.Sleep(1*time.Second)
}

func do()  {
	httpclient.
		WithHeader("1","1").
		WithHeader("2","2").
		WithHeader("3","3").
		WithHeader("4","4").Get("google.com")
}
```

fatal error: concurrent map writes

goroutine 20 [running]:
runtime.throw(0x122da43, 0x15)
	C:/Program Files/Go/src/runtime/panic.go:1117 +0x79 fp=0xc000055ed0 sp=0xc000055ea0 pc=0xf99419
runtime.mapassign_faststr(0x11e16c0, 0xc00001e030, 0x1228229, 0x1, 0x0)
	C:/Program Files/Go/src/runtime/map_faststr.go:211 +0x411 fp=0xc000055f38 sp=0xc000055ed0 pc=0xf74e11
github.com/ddliu/go-httpclient.(*HttpClient).WithHeader(...)

**Comment by ddliu** [comment]
Make sure to call `Begin()` for each request in case of concurrency as described in README.

```
    httpclient.
        Begin().
        WithHeader("Req-A", "a").
        Get("http://google.com")
```

**Comment by sunyuan300** [comment]
Thanks!
