### ISSUE TITLE
I/o timeout

### ISSUE THREAD

**Issue by shanweidi** [ddliu/go-httpclient#49]
默认客户端设置了超时时间20秒，调用外部接口error返回超时，前后记录时间实际只花了40毫秒

**Comment by ddliu** [comment]
Please provide code example and detailed error information.

**Comment by shanweidi** [comment]
> Please provide code example and detailed error information.

作为httpclient的封装，超时时间的设置本意往往是一次http请求的发起到收到response的间隔时间，代码里将这个时间设置到了tcp链接层面的：
`if timeout > 0 {
			conn.SetDeadline(time.Now().Add(timeout))
		}`
应该在真正执行http调用的Do函数内new HttpClient的时候将这个超时设置进去：
`c := &http.Client{
		Transport:     transport,
		CheckRedirect: redirect,
		Jar:           jar,
		Timeout: timeout,
	}
`

**Comment by ddliu** [comment]
Fixed. 

Note that go 1.12 is deprecated as the `timeout` option is supported after go v1.13.
