### ISSUE TITLE
how set OPT_PROXY

### ISSUE THREAD

**Issue by mohamadpk** [ddliu/go-httpclient#9]
hi i try to set OPT_PROXY.by this code
proxy:="127.0.0.1:8080"
cli:=httpclient.NewHttpClient()
cli.WithOption(httpclient.OPT_PROXYTYPE,httpclient.PROXY_HTTP)
cli.WithOption(httpclient.OPT_PROXY,proxy)

this not work...Please help me

**Comment by ddliu** [comment]
Hi, this does work for the *next* request.

If you want to set proxy for all requests by the client, try to set up with the `Defaults` method:

```go
cli.Defaults(httpclient.Map {
    httpclient.OPT_PROXY: "127.0.0.1:8080",
    // ANY_OTHER_OPTIONS...
})
```

Note what the `WithXXX` methods only affect the next request, you can chain them together to customise each of your requests.

**Comment by mohamadpk** [comment]
tnx for help...this work now
